from pydantic import BaseModel, Field, conint

class FoodAndActivityPreferences(BaseModel):
    adding_salt: conint(ge=1, le=11) = Field(description="Adding salt to foods")
    aniseed: conint(ge=1, le=11) = Field(description="Aniseed")
    apple_juice: conint(ge=1, le=11) = Field(description="Apple juice")
    apples: conint(ge=1, le=11) = Field(description="Apples")
    asparagus: conint(ge=1, le=11) = Field(description="Asparagus")
    aubergine: conint(ge=1, le=11) = Field(description="Aubergine")
    avocados: conint(ge=1, le=11) = Field(description="Avocados")
    bacon: conint(ge=1, le=11) = Field(description="Bacon")
    baked_steamed_fish: conint(ge=1, le=11) = Field(description="Baked/steamed fish")
    bananas: conint(ge=1, le=11) = Field(description="Bananas")
    barbequed_grilled_meat: conint(ge=1, le=11) = Field(description="Barbequed or grilled meat")
    beef_steak: conint(ge=1, le=11) = Field(description="Beef steak")
    beetroot: conint(ge=1, le=11) = Field(description="Beetroot")
    bell_pepper: conint(ge=1, le=11) = Field(description="Bell pepper")
    bicycling: conint(ge=1, le=11) = Field(description="Bicycling")
    biscuits: conint(ge=1, le=11) = Field(description="Biscuits")
    bitter_foods: conint(ge=1, le=11) = Field(description="Bitter foods")
    bitter_ale: conint(ge=1, le=11) = Field(description="Bitter/ale")
    black_olives: conint(ge=1, le=11) = Field(description="Black olives")
    black_pepper: conint(ge=1, le=11) = Field(description="Black pepper")
    blue_cheese: conint(ge=1, le=11) = Field(description="Blue cheese")
    bolognese_sauce: conint(ge=1, le=11) = Field(description="Bolognese sauce")
    broad_beans: conint(ge=1, le=11) = Field(description="Broad beans")
    broccoli: conint(ge=1, le=11) = Field(description="Broccoli")
    brown_rice: conint(ge=1, le=11) = Field(description="Brown rice")
    brussel_sprouts: conint(ge=1, le=11) = Field(description="Brussel sprouts")
    burgers_meat: conint(ge=1, le=11) = Field(description="Burgers (meat)")
    burn_spicy_foods: conint(ge=1, le=11) = Field(description="Burn of spicy foods")
    butter_bread: conint(ge=1, le=11) = Field(description="Butter on bread")
    butternut_squash: conint(ge=1, le=11) = Field(description="Butternut squash")
    cabbage: conint(ge=1, le=11) = Field(description="Cabbage")
    cake: conint(ge=1, le=11) = Field(description="Cake")
    cake_icing: conint(ge=1, le=11) = Field(description="Cake icing")
    capers: conint(ge=1, le=11) = Field(description="Capers")
    cauliflower: conint(ge=1, le=11) = Field(description="Cauliflower")
    cereal_granola_bar: conint(ge=1, le=11) = Field(description="Cereal/granola bar")
    cheesecake: conint(ge=1, le=11) = Field(description="Cheesecake")
    cherries: conint(ge=1, le=11) = Field(description="Cherries")
    chicken: conint(ge=1, le=11) = Field(description="Chicken")
    chilli_pepper: conint(ge=1, le=11) = Field(description="Chilli pepper")
    chips_french_fries: conint(ge=1, le=11) = Field(description="Chips/French fries")
    cigarette_smoking: conint(ge=1, le=11) = Field(description="Cigarette smoking")
    cod: conint(ge=1, le=11) = Field(description="Cod")
    coffee_with_sugar: conint(ge=1, le=11) = Field(description="Coffee with sugar")
    coffee_without_sugar: conint(ge=1, le=11) = Field(description="Coffee without sugar")
    coriander: conint(ge=1, le=11) = Field(description="Coriander")
    corn_flakes: conint(ge=1, le=11) = Field(description="Corn flakes")
    cream: conint(ge=1, le=11) = Field(description="Cream")
    croissant: conint(ge=1, le=11) = Field(description="Croissant")
    cucumber: conint(ge=1, le=11) = Field(description="Cucumber")
    curry: conint(ge=1, le=11) = Field(description="Curry")
    dairy_products: conint(ge=1, le=11) = Field(description="Dairy products")
    dark_chocolate: conint(ge=1, le=11) = Field(description="Dark chocolate")
    diet_fizzy_drinks: conint(ge=1, le=11) = Field(description="Diet fizzy drinks")
    dried_fruit: conint(ge=1, le=11) = Field(description="Dried fruit")
    eggs: conint(ge=1, le=11) = Field(description="Eggs")
    exercising_alone: conint(ge=1, le=11) = Field(description="Exercising alone")
    exercising_with_others: conint(ge=1, le=11) = Field(description="Exercising with others")
    extra_virgin_olive_oil: conint(ge=1, le=11) = Field(description="Extra virgin olive oil")
    fatty_foods: conint(ge=1, le=11) = Field(description="Fatty foods")
    fresh_tomatoes: conint(ge=1, le=11) = Field(description="Fresh tomatoes")
    fried_chicken: conint(ge=1, le=11) = Field(description="Fried chicken")
    fried_battered_fish: conint(ge=1, le=11) = Field(description="Fried/battered fish")
    fruit: conint(ge=1, le=11) = Field(description="Fruit")
    garlic: conint(ge=1, le=11) = Field(description="Garlic")
    gherkins: conint(ge=1, le=11) = Field(description="Gherkins")
    globe_artichoke: conint(ge=1, le=11) = Field(description="Globe artichoke")
    goats_cheese: conint(ge=1, le=11) = Field(description="Goat's cheese")
    going_cafe: conint(ge=1, le=11) = Field(description="Going to a café")
    going_gym: conint(ge=1, le=11) = Field(description="Going to the gym")
    going_pub: conint(ge=1, le=11) = Field(description="Going to the pub")
    grapefruit: conint(ge=1, le=11) = Field(description="Grapefruit")
    green_olives: conint(ge=1, le=11) = Field(description="Green olives")
    haddock: conint(ge=1, le=11) = Field(description="Haddock")
    ham: conint(ge=1, le=11) = Field(description="Ham")
    hard_cheese: conint(ge=1, le=11) = Field(description="Hard cheese")
    herring: conint(ge=1, le=11) = Field(description="Herring")
    honey: conint(ge=1, le=11) = Field(description="Honey")
    horseradish_wasabi: conint(ge=1, le=11) = Field(description="Horseradish/wasabi")
    ice_cream: conint(ge=1, le=11) = Field(description="Ice cream")
    jam: conint(ge=1, le=11) = Field(description="Jam")
    kiwi_fruit: conint(ge=1, le=11) = Field(description="Kiwi fruit")
    lager: conint(ge=1, le=11) = Field(description="Lager")
    lamb: conint(ge=1, le=11) = Field(description="Lamb")
    lemons: conint(ge=1, le=11) = Field(description="Lemons")
    lentils_beans: conint(ge=1, le=11) = Field(description="Lentils/beans")
    liver: conint(ge=1, le=11) = Field(description="Liver")
    mackerel: conint(ge=1, le=11) = Field(description="Mackerel")
    marzipan: conint(ge=1, le=11) = Field(description="Marzipan")
    mayonnaise: conint(ge=1, le=11) = Field(description="Mayonnaise")
    melon: conint(ge=1, le=11) = Field(description="Melon")
    milk_chocolate: conint(ge=1, le=11) = Field(description="Milk chocolate")
    mushrooms: conint(ge=1, le=11) = Field(description="Mushrooms")
    onions: conint(ge=1, le=11) = Field(description="Onions")
    orange_juice: conint(ge=1, le=11) = Field(description="Orange juice")
    oranges: conint(ge=1, le=11) = Field(description="Oranges")
    pasta: conint(ge=1, le=11) = Field(description="Pasta")
    pears: conint(ge=1, le=11) = Field(description="Pears")
    pizza: conint(ge=1, le=11) = Field(description="Pizza")
    plain_yogurt: conint(ge=1, le=11) = Field(description="Plain yogurt")
    plums: conint(ge=1, le=11) = Field(description="Plums")
    pollock: conint(ge=1, le=11) = Field(description="Pollock")
    pork_chop: conint(ge=1, le=11) = Field(description="Pork chop")
    porridge: conint(ge=1, le=11) = Field(description="Porridge")
    potato_crisps: conint(ge=1, le=11) = Field(description="Potato crisps")
    potatoes: conint(ge=1, le=11) = Field(description="Potatoes")
    prawns: conint(ge=1, le=11) = Field(description="Prawns")
    raw_carrots: conint(ge=1, le=11) = Field(description="Raw carrots")
    red_meat: conint(ge=1, le=11) = Field(description="Red meat")
    red_wine: conint(ge=1, le=11) = Field(description="Red wine")
    regular_fizzy_drinks: conint(ge=1, le=11) = Field(description="Regular (non-diet) fizzy drinks")
    roast_chicken: conint(ge=1, le=11) = Field(description="Roast chicken")
    salad_dressing: conint(ge=1, le=11) = Field(description="Salad dressing")
    salad_leaves: conint(ge=1, le=11) = Field(description="Salad leaves")
    salami: conint(ge=1, le=11) = Field(description="Salami")
    salmon: conint(ge=1, le=11) = Field(description="Salmon")
    salty_foods: conint(ge=1, le=11) = Field(description="Salty foods")
    salty_pretzels: conint(ge=1, le=11) = Field(description="Salty pretzels")
    sardines: conint(ge=1, le=11) = Field(description="Sardines")
    sausages_meat: conint(ge=1, le=11) = Field(description="Sausages (meat)")
    savoury_biscuits: conint(ge=1, le=11) = Field(description="Savoury biscuits")
    shellfish_other: conint(ge=1, le=11) = Field(description="Shellfish (other than prawns)")
    skimmed_milk: conint(ge=1, le=11) = Field(description="Skimmed milk")
    smoked_fish: conint(ge=1, le=11) = Field(description="Smoked fish")
    soft_cheese: conint(ge=1, le=11) = Field(description="Soft cheese")
    soy_sauce: conint(ge=1, le=11) = Field(description="Soy sauce")
    soya_milk: conint(ge=1, le=11) = Field(description="Soya milk")
    spicy_foods: conint(ge=1, le=11) = Field(description="Spicy foods")
    spinach: conint(ge=1, le=11) = Field(description="Spinach")
    spirits: conint(ge=1, le=11) = Field(description="Spirits (e.g. vodka, gin, whisky etc.)")
    strawberries: conint(ge=1, le=11) = Field(description="Strawberries")
    sweet_coffee_drinks: conint(ge=1, le=11) = Field(description="Sweet coffee house drinks (e.g. Mocha's, Frappucino's, flavoured Latte's)")
    sweet_foods: conint(ge=1, le=11) = Field(description="Sweet foods")
    taking_stairs: conint(ge=1, le=11) = Field(description="Taking the stairs")
    tea_with_sugar: conint(ge=1, le=11) = Field(description="Tea with sugar")
    tea_without_sugar: conint(ge=1, le=11) = Field(description="Tea without sugar")
    tomato_ketchup: conint(ge=1, le=11) = Field(description="Tomato ketchup")
    tinned_tuna: conint(ge=1, le=11) = Field(description="Tinned tuna")
    turnip_white: conint(ge=1, le=11) = Field(description="Turnip (white)")
    vegetables: conint(ge=1, le=11) = Field(description="Vegetables")
    vinegar: conint(ge=1, le=11) = Field(description="Vinegar")
    watching_television: conint(ge=1, le=11) = Field(description="Watching television")
    whisky: conint(ge=1, le=11) = Field(description="Whisky")
    white_bread: conint(ge=1, le=11) = Field(description="White bread")
    white_rice: conint(ge=1, le=11) = Field(description="White rice")
    white_wine: conint(ge=1, le=11) = Field(description="White wine")
    whole_grain_cereal: conint(ge=1, le=11) = Field(description="Whole grain breakfast cereal")
    whole_milk: conint(ge=1, le=11) = Field(description="Whole milk")
    wholemeal_bread: conint(ge=1, le=11) = Field(description="Wholemeal bread")
    working_up_sweat: conint(ge=1, le=11) = Field(description="Working up a sweat")

# from langchain_core.utils.function_calling import convert_to_openai_function
# print(convert_to_openai_function(FoodAndActivityPreferences))

class CheckFoods(BaseModel):
    adding_salt: conint(ge=1, le=11) = Field(description="Favorite food 1")
    adding_salt: conint(ge=1, le=11) = Field(description="Favorite food 1")
    adding_salt: conint(ge=1, le=11) = Field(description="Favorite food 1")
    adding_salt: conint(ge=1, le=11) = Field(description="Disliked food 1")
    adding_salt: conint(ge=1, le=11) = Field(description="Favorite food 1")
    adding_salt: conint(ge=1, le=11) = Field(description="Favorite food 1")
