from pydantic import BaseModel, Field

class FoodAndActivityQuestionnaire(BaseModel):
    # Instead of using conint, we'll use regular int with Field constraints
    adding_salt: int = Field(description="Adding salt to foods")
    aniseed: int = Field(description="Aniseed")
    apple_juice: int = Field(description="Apple juice")
    apples: int = Field(description="Apples")
    asparagus: int = Field(description="Asparagus")
    aubergine: int = Field(description="Aubergine")
    avocados: int = Field(description="Avocados")
    bacon: int = Field(description="Bacon")
    baked_steamed_fish: int = Field(description="Baked/steamed fish")
    bananas: int = Field(description="Bananas")
    barbequed_grilled_meat: int = Field(description="Barbequed or grilled meat")
    beef_steak: int = Field(description="Beef steak")
    beetroot: int = Field(description="Beetroot")
    bell_pepper: int = Field(description="Bell pepper")
    bicycling: int = Field(description="Bicycling")
    biscuits: int = Field(description="Biscuits")
    bitter_foods: int = Field(description="Bitter foods")
    bitter_ale: int = Field(description="Bitter/ale")
    black_olives: int = Field(description="Black olives")
    black_pepper: int = Field(description="Black pepper")
    blue_cheese: int = Field(description="Blue cheese")
    bolognese_sauce: int = Field(description="Bolognese sauce")
    broad_beans: int = Field(description="Broad beans")
    broccoli: int = Field(description="Broccoli")
    brown_rice: int = Field(description="Brown rice")
    brussel_sprouts: int = Field(description="Brussel sprouts")
    burgers_meat: int = Field(description="Burgers (meat)")
    burn_spicy_foods: int = Field(description="Burn of spicy foods")
    butter_bread: int = Field(description="Butter on bread")
    butternut_squash: int = Field(description="Butternut squash")
    cabbage: int = Field(description="Cabbage")
    cake: int = Field(description="Cake")
    cake_icing: int = Field(description="Cake icing")
    capers: int = Field(description="Capers")
    cauliflower: int = Field(description="Cauliflower")
    cereal_granola_bar: int = Field(description="Cereal/granola bar")
    cheesecake: int = Field(description="Cheesecake")
    cherries: int = Field(description="Cherries")
    chicken: int = Field(description="Chicken")
    chilli_pepper: int = Field(description="Chilli pepper")
    chips_french_fries: int = Field(description="Chips/French fries")
    cigarette_smoking: int = Field(description="Cigarette smoking")
    cod: int = Field(description="Cod")
    coffee_with_sugar: int = Field(description="Coffee with sugar")
    coffee_without_sugar: int = Field(description="Coffee without sugar")
    coriander: int = Field(description="Coriander")
    corn_flakes: int = Field(description="Corn flakes")
    cream: int = Field(description="Cream")
    croissant: int = Field(description="Croissant")
    cucumber: int = Field(description="Cucumber")
    curry: int = Field(description="Curry")
    dairy_products: int = Field(description="Dairy products")
    dark_chocolate: int = Field(description="Dark chocolate")
    diet_fizzy_drinks: int = Field(description="Diet fizzy drinks")
    dried_fruit: int = Field(description="Dried fruit")
    eggs: int = Field(description="Eggs")
    exercising_alone: int = Field(description="Exercising alone")
    exercising_with_others: int = Field(description="Exercising with others")
    extra_virgin_olive_oil: int = Field(description="Extra virgin olive oil")
    fatty_foods: int = Field(description="Fatty foods")
    fresh_tomatoes: int = Field(description="Fresh tomatoes")
    fried_chicken: int = Field(description="Fried chicken")
    fried_battered_fish: int = Field(description="Fried/battered fish")
    fruit: int = Field(description="Fruit")
    garlic: int = Field(description="Garlic")
    gherkins: int = Field(description="Gherkins")
    globe_artichoke: int = Field(description="Globe artichoke")
    goats_cheese: int = Field(description="Goat's cheese")
    going_cafe: int = Field(description="Going to a café")
    going_gym: int = Field(description="Going to the gym")
    going_pub: int = Field(description="Going to the pub")
    grapefruit: int = Field(description="Grapefruit")
    green_olives: int = Field(description="Green olives")
    haddock: int = Field(description="Haddock")
    ham: int = Field(description="Ham")
    hard_cheese: int = Field(description="Hard cheese")
    herring: int = Field(description="Herring")
    honey: int = Field(description="Honey")
    horseradish_wasabi: int = Field(description="Horseradish/wasabi")
    ice_cream: int = Field(description="Ice cream")
    jam: int = Field(description="Jam")
    kiwi_fruit: int = Field(description="Kiwi fruit")
    lager: int = Field(description="Lager")
    lamb: int = Field(description="Lamb")
    lemons: int = Field(description="Lemons")
    lentils_beans: int = Field(description="Lentils/beans")
    liver: int = Field(description="Liver")
    mackerel: int = Field(description="Mackerel")
    marzipan: int = Field(description="Marzipan")
    mayonnaise: int = Field(description="Mayonnaise")
    melon: int = Field(description="Melon")
    milk_chocolate: int = Field(description="Milk chocolate")
    mushrooms: int = Field(description="Mushrooms")
    onions: int = Field(description="Onions")
    orange_juice: int = Field(description="Orange juice")
    oranges: int = Field(description="Oranges")
    pasta: int = Field(description="Pasta")
    pears: int = Field(description="Pears")
    pizza: int = Field(description="Pizza")
    plain_yogurt: int = Field(description="Plain yogurt")
    plums: int = Field(description="Plums")
    pollock: int = Field(description="Pollock")
    pork_chop: int = Field(description="Pork chop")
    porridge: int = Field(description="Porridge")
    potato_crisps: int = Field(description="Potato crisps")
    potatoes: int = Field(description="Potatoes")
    prawns: int = Field(description="Prawns")
    raw_carrots: int = Field(description="Raw carrots")
    red_meat: int = Field(description="Red meat")
    red_wine: int = Field(description="Red wine")
    regular_fizzy_drinks: int = Field(description="Regular (non-diet) fizzy drinks")
    roast_chicken: int = Field(description="Roast chicken")
    salad_dressing: int = Field(description="Salad dressing")
    salad_leaves: int = Field(description="Salad leaves")
    salami: int = Field(description="Salami")
    salmon: int = Field(description="Salmon")
    salty_foods: int = Field(description="Salty foods")
    salty_pretzels: int = Field(description="Salty pretzels")
    sardines: int = Field(description="Sardines")
    sausages_meat: int = Field(description="Sausages (meat)")
    savoury_biscuits: int = Field(description="Savoury biscuits")
    shellfish_other: int = Field(description="Shellfish (other than prawns)")
    skimmed_milk: int = Field(description="Skimmed milk")
    smoked_fish: int = Field(description="Smoked fish")
    soft_cheese: int = Field(description="Soft cheese")
    soy_sauce: int = Field(description="Soy sauce")
    soya_milk: int = Field(description="Soya milk")
    spicy_foods: int = Field(description="Spicy foods")
    spinach: int = Field(description="Spinach")
    spirits: int = Field(description="Spirits (e.g. vodka, gin, whisky etc.)")
    strawberries: int = Field(description="Strawberries")
    sweet_coffee_drinks: int = Field(description="Sweet coffee house drinks (e.g. Mocha's, Frappucino's, flavoured Latte's)")
    sweet_foods: int = Field(description="Sweet foods")
    taking_stairs: int = Field(description="Taking the stairs")
    tea_with_sugar: int = Field(description="Tea with sugar")
    tea_without_sugar: int = Field(description="Tea without sugar")
    tomato_ketchup: int = Field(description="Tomato ketchup")
    tinned_tuna: int = Field(description="Tinned tuna")
    turnip_white: int = Field(description="Turnip (white)")
    vegetables: int = Field(description="Vegetables")
    vinegar: int = Field(description="Vinegar")
    watching_television: int = Field(description="Watching television")
    whisky: int = Field(description="Whisky")
    white_bread: int = Field(description="White bread")
    white_rice: int = Field(description="White rice")
    white_wine: int = Field(description="White wine")
    whole_grain_cereal: int = Field(description="Whole grain breakfast cereal")
    whole_milk: int = Field(description="Whole milk")
    wholemeal_bread: int = Field(description="Wholemeal bread")
    working_up_sweat: int = Field(description="Working up a sweat")
